default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: carvalhoautocenter_development
  username: <%= ENV['DB_USERNAME'] || "edsonrodas" %>
  password: <%= ENV['DB_PASSWORD'] || "edilena26" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>

test:
  <<: *default
  database: carvalhoautocenter_test
  username: <%= ENV['DB_USERNAME'] || "edsonrodas" %>
  password: <%= ENV['DB_PASSWORD'] || "edilena26" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || "carvalhoautocenter_production" %>
  username: <%= ENV['DB_USERNAME'] || "edsonrodas" %>
  password: <%= ENV['DB_PASSWORD'] || "edilena26" %>
  host: <%= ENV['DB_HOST'] || "db" %>
